name: 'Build Pages'
description: 'A build tool utilizing JavaScripts template literals to render HTML pages.'
inputs:
  folder:
    description: 'The folder containing the pages to build.'
    required: false
  config:
    description: 'The configuration file for the build.'
    required: false
outputs:
  folder:
    description: 'The folder containing the built pages.'
runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'
      - run: npm ci
        shell: bash
      - run: node action/action.mjs
        shell: bash
