name: 'Build Pages'
description: 'A build tool utilizing JavaScripts template literals to render HTML pages.'
inputs:
  folder:
    description: 'The folder containing the pages to build.'
    required: false
  config:
    description: 'The configuration file for the build.'
    required: false
outputs:
  folder:
    description: 'The folder containing the built pages.'
    value: ${{ steps.build.outputs.folder }}
runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 'latest'
      - run: cd ${GITHUB_ACTION_PATH} && npm ci
        shell: bash
      - id: build
        run: node ${GITHUB_ACTION_PATH}/src/action.mjs
        shell: bash
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT
          INPUT_FOLDER: ${{ inputs.folder }}
          INPUT_CONFIG: ${{ inputs.config }}
          HOST: ${{ env.HOST }}
          PORT: ${{ env.PORT }}
          PATHNAME: ${{ env.PATHNAME }}
