import * as process from 'node:process'

import * as htmlModule from './modules/html/html.mjs'
import * as pagesModule from './modules/pages/pages.mjs'
import * as jsonModule from './modules/json/json.mjs'
import * as cssModule from './modules/css/css.mjs'
import * as jsModule from './modules/js/js.mjs'

const host = process.env.PAGE_HOST || 'localhost'
const port = process.env.PAGE_PORT || '8080'
const path = process.env.PAGE_PATH || ''
const protocol = port === '443' ? 'https' : 'http'

export const baseURI = new URL(path, `${protocol}://${host}${port === '80' || port === '443' ? '' : `:${port}`}`)

export const modules = [pagesModule, htmlModule, jsonModule, cssModule, jsModule]

export const serve = {
  partials: false,
}

export const build = {
  output: './dist',
  ignore: [
    './translations/**',
    '**/*.mjs'
  ],
  parallel: undefined,
}

export const js = {
  minify: true,
  target: './.browserslistrc',
}

export const html = {
  references: {
    resolve: true,
  },
  js: {
    minify: true,
    integrity: true,
  },
  css: {
    minify: true,
    integrity: true, // @todo: add support for CSS integrity
  },
  minify: {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    conservativeCollapse: false,
    continueOnParseError: true,
    customAttrAssign: [],
    customAttrCollapse: null,
    customAttrSurround: [],
    customEventAttributes: [],
    decodeEntities: true,
    html5: true,
    ignoreCustomComments: [],
    ignoreCustomFragments: [],
    includeAutoGeneratedTags: false,
    keepClosingSlash: true,
    maxLineLength: null,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    noNewlinesBeforeTagClose: true,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: false,
    processScripts: [],
    quoteCharacter: '"',
    removeAttributeQuotes: false,
    removeComments: true,
    removeEmptyAttributes: false,
    removeEmptyElements: false,
    removeOptionalTags: false,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: false,
    removeStyleLinkTypeAttributes: false,
    removeTagWhitespace: false,
    sortAttributes: true,
    sortClassName: true,
    trimCustomFragments: true,
    useShortDoctype: true,
  },
}
