name: Website

on:
  push:
    branches: [ latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - id: build
      uses: plushveil/pages@latest
      with:
        folder: 'website'

    - name: Checkout GitHub Pages Branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Deploy
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name 'CNAME' ! -name '.git' -exec rm -rf {} +
        cp -r ${{ steps.build.outputs.folder }}/* .
        git add .
        git commit -m "Deploy"
        git push
