name: Website

on:
  push:
    branches: [ latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: plushveil/pages@latest
      with:
        folder: 'website'
