name: CD

on:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: cd npm-package && npm install

      - name: Run tests
        run: cd npm-package && npm test

  publish-package:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build package artifacts
        run: |
          cd npm-package
          npm ci --include=dev
          npm run build

      - name: Publish package
        run: |
          cd npm-package
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to GitHub Package Registry
        run: |
          cd npm-package
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm config set @plushveil:registry https://npm.pkg.github.com
          npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-extension:
    needs:
      - build
      - publish-package
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Publish extension
        run: |
          cd npm-package
          npm ci --include=dev
          rm -f ../vscode-extension/*.tgz
          npm pack --pack-destination ../vscode-extension --silent > /dev/null
          PACKAGE_TGZ=$(basename "$(ls -1t ../vscode-extension/*.tgz | head -n1)")
          cd ..

          cd vscode-extension
          npm pkg set dependencies.@plushveil/pages=file:./${PACKAGE_TGZ}
          npm install --include=dev --ignore-scripts
          npm run build

          npm install -g @vscode/vsce --allow-scripts=@vscode/vsce-sign,keytar
          vsce package --skip-license
          vsce publish --pat ${{ secrets.VSCODE_TOKEN }} || true

  publish-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: website
        uses: plushveil/pages@latest
        with:
          folder: "website"
        env:
          HOST: plushveil.github.io
          PORT: 443
          PATHNAME: /pages/

      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          ls -A | grep -v '^\.git\|CNAME\|preview' | xargs rm -rf
          cp -r ${{steps.website.outputs.folder}}/* .
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ github.actor }}: ${{ github.event.head_commit.message }}" || exit 0
          git push

  publish-ghcr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (optional, for multi-arch images)
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:npm-package"
          file: Dockerfile
          push: true
          tags: ghcr.io/plushveil/pages:latest

      - name: Logout from GHCR
        run: docker logout ghcr.io
